apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dbeaver.name" . }}-env
  labels:
    {{- include "dbeaver.labels" . | nindent 4 }}
type: Opaque
data:
  CB_SERVER_NAME: VGVzdA==
  CB_SERVER_URL: aHR0cHM6Ly9jbG91ZGJlYXZlci5kb21haW4uY29tOjEwMDAwLw==
  CB_ADMIN_NAME: YWRtaW4=
  CB_ADMIN_PASSWORD: YWRtaW4=