apiVersion: v1
kind: Service
metadata:
  name: {{ include "dbeaver.name" . }}
  labels:
    {{- include "dbeaver.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: {{ .Values.service.name }}
      protocol: {{ .Values.service.protocol }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    {{- include "dbeaver.selectorLabels" . | nindent 4 }}